### ISSUE TITLE
PathSchemeSelectionTests broken

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AuthSamples#38]
PathSchemeSelectionTests, DynamicSchemeTests, and IdentityExternalClaimsTests are all failing with errors like

http://aspnetci/viewLog.html?buildId=454232&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR
```
[00:00:06] :	 [Step 3/4]   AuthSamples           |   System.InvalidOperationException: Cannot find reference assembly 'System.ComponentModel.Composition.dll' file for package System.ComponentModel.Composition
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
[00:00:06] :	 [Step 3/4]   AuthSamples           |      at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
```

@javiercn can you take a look?
cc @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
What was the resolution here?

**Comment by Tratcher** [comment]
https://github.com/aspnet/AuthSamples/pull/39
